version: '3.5'
services:

  traefik:
    container_name: traefik
    image: traefik:v2.2
    ports:
      - "80:80"
      - "9090:8080"
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yaml:/traefik.yml:ro
    networks:
      - traefik-net
    labels:
      - "traefik.port=9090"
      - "traefik.http.routers.api.rule=Host(`traefik.mydomain.test`)"
      - "traefik.http.routers.api.service=api@internal"
    restart: unless-stopped

  doodle_redis:
    container_name: doodle_redis
    image: redis:alpine
    ports:
      - "6379:6379"
    expose:
      - "6379"
    networks:
      - inter-net

  doodle_mysql:
    container_name: doodle_mysql
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    working_dir: /application
    depends_on:
      - traefik
    volumes:
      - .:/application
      - ./docker/mysql/doodle:/var/lib/mysql
      # - ./docker/mysql/mysql.conf:/etc/mysql/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=doodle
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
      - SERVICE_NAME=doodle_mysql
    ports:
      - "3306:3306"
    security_opt:
      - seccomp:unconfined
    networks:
      - inter-net

  doodle_vuejs:
    container_name: doodle_vuejs
    build:
      context: .
      dockerfile: ./DockerfileVue
      target: vueapp

    working_dir: /application
    volumes:
      - ./docker/nginx-vue/nginx.conf:/etc/nginx/nginx.conf
    expose:
      - "80"
      - "443"
    labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-net"
        - "traefik.port=80"
        - "traefik.http.routers.doodle_vuejs.rule=PathPrefix(`/admin`)"

    networks:
      - inter-net
      - traefik-net

  doodle_api:
    container_name: doodle_api
    image: nginx:alpine
    working_dir: /application
    depends_on:
      - doodle_php
    volumes:
#      - ./laravel:/application
      - ./docker/nginx-api/nginx.conf:/etc/nginx/conf.d/default.conf
    expose:
      - "80"
      - "443"
      - "9000"
    labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-net"
        - "traefik.port=80"
        - "traefik.http.routers.doodle_api.rule=PathPrefix(`/`)"
    networks:
      - inter-net
      - traefik-net

  doodle_php:
    container_name: doodle_php
    build:
      context: .
      dockerfile: ./DockerfilePhp
      target: php72
    working_dir: /application
    depends_on:
      - doodle_mysql
    volumes:
      - ./laravel:/application
      - ./laravel/supervisord.conf:/etc/supervisord.conf
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
    networks:
      - inter-net
      - traefik-net

networks:
  inter-net:
    external: true
  traefik-net:
    external: true


