#!/bin/bash
echo "*** DELETE ALL ***"
echo ") remove vendor folder"
echo ") remove database folder"
echo    # move to a new line
read -p "Are you sure? [y/n] " -n 1 -r
echo    #  move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
	echo DELETING...
	rm -R laravel/vendor
	rm -R docker/mysql/doodle
fi