#!/bin/bash

cp laravel/.env.example laravel/.env
cd vuecli;npm install;cd ..
docker-compose build
docker-compose up -d
docker ps
docker/doexec doodle_php composer install
docker/doexec doodle_php php artisan key:generate
docker/doexec doodle_php php artisan jwt:secret
